[package]
name = "nakamoto"
description = "Privacy-preserving Bitcoin light-client"
documentation = "https://docs.rs/nakamoto"
homepage = "https://cloudhead.io/nakamoto/"
repository = "https://github.com/cloudhead/nakamoto"
readme = "README.md"
license = "MIT"
version = "0.4.0"
authors = ["Alexis Sellier <self@cloudhead.io>"]
edition = "2021"

[workspace]
members = [
  "common",
  "p2p",
  "chain",
  "node",
  "test",
  "client",
  "wallet",
  "net",
]
default-members = [
  "common",
  "p2p",
  "chain",
  "test",
  "client",
  "net",
]

[features]
default = [
  "nakamoto-client",
  "nakamoto-chain",
  "nakamoto-p2p",
  "nakamoto-common",
  "nakamoto-net",
  "nakamoto-net-poll"
]
polling = [
  "nakamoto-client",
  "nakamoto-chain",
  "nakamoto-p2p",
  "nakamoto-common",
  "nakamoto-net",
  "nakamoto-net-polling"
]

[dependencies]
nakamoto-common = { version = "0.4.0", path = "./common", optional = true }
nakamoto-node = { version = "0.4.0", path = "./node", optional = true }
nakamoto-client = { version = "0.4.0", path = "./client", optional = true }
nakamoto-chain = { version = "0.4.0", path = "./chain", optional = true }
nakamoto-p2p = { version = "0.4.0", path = "./p2p", optional = true }
nakamoto-test = { version = "0.4.0", path = "./test", optional = true }
nakamoto-wallet = { version = "0.4.0", path = "./wallet", optional = true }
nakamoto-net = { version = "0.4.0", path = "./net", optional = true }
nakamoto-net-poll = { version = "0.4.0", path = "./net/poll", optional = true }
nakamoto-net-polling = { version = "0.4.0", path = "./net/polling", optional = true }
